/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FrHeader {
    }
    interface FrLogo {
        "large"?: boolean;
        /**
          * Global size of the logo with the Marianne and the french motto The default size is medium and does not need to be specified
         */
        "small"?: boolean;
    }
    interface FrSearch {
    }
    interface FrService {
        "large"?: boolean;
        /**
          * Global size of the logo with the Marianne and the french motto The default size is medium and does not need to be specified
         */
        "small"?: boolean;
    }
}
export interface FrSearchCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFrSearchElement;
}
declare global {
    interface HTMLFrHeaderElement extends Components.FrHeader, HTMLStencilElement {
    }
    var HTMLFrHeaderElement: {
        prototype: HTMLFrHeaderElement;
        new (): HTMLFrHeaderElement;
    };
    interface HTMLFrLogoElement extends Components.FrLogo, HTMLStencilElement {
    }
    var HTMLFrLogoElement: {
        prototype: HTMLFrLogoElement;
        new (): HTMLFrLogoElement;
    };
    interface HTMLFrSearchElement extends Components.FrSearch, HTMLStencilElement {
    }
    var HTMLFrSearchElement: {
        prototype: HTMLFrSearchElement;
        new (): HTMLFrSearchElement;
    };
    interface HTMLFrServiceElement extends Components.FrService, HTMLStencilElement {
    }
    var HTMLFrServiceElement: {
        prototype: HTMLFrServiceElement;
        new (): HTMLFrServiceElement;
    };
    interface HTMLElementTagNameMap {
        "fr-header": HTMLFrHeaderElement;
        "fr-logo": HTMLFrLogoElement;
        "fr-search": HTMLFrSearchElement;
        "fr-service": HTMLFrServiceElement;
    }
}
declare namespace LocalJSX {
    interface FrHeader {
    }
    interface FrLogo {
        "large"?: boolean;
        /**
          * Global size of the logo with the Marianne and the french motto The default size is medium and does not need to be specified
         */
        "small"?: boolean;
    }
    interface FrSearch {
        "onFr-search-execute"?: (event: FrSearchCustomEvent<any>) => void;
    }
    interface FrService {
        "large"?: boolean;
        /**
          * Global size of the logo with the Marianne and the french motto The default size is medium and does not need to be specified
         */
        "small"?: boolean;
    }
    interface IntrinsicElements {
        "fr-header": FrHeader;
        "fr-logo": FrLogo;
        "fr-search": FrSearch;
        "fr-service": FrService;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fr-header": LocalJSX.FrHeader & JSXBase.HTMLAttributes<HTMLFrHeaderElement>;
            "fr-logo": LocalJSX.FrLogo & JSXBase.HTMLAttributes<HTMLFrLogoElement>;
            "fr-search": LocalJSX.FrSearch & JSXBase.HTMLAttributes<HTMLFrSearchElement>;
            "fr-service": LocalJSX.FrService & JSXBase.HTMLAttributes<HTMLFrServiceElement>;
        }
    }
}
