/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FrAccordion {
        "toto": string;
    }
    interface FrFooter {
    }
    interface FrHeader {
    }
    interface FrHeaderMenuLinks {
        "ariaCurrentLink": string;
        "hrefLink": string;
        "textLink": string;
        "titleLink": string;
    }
    interface FrHeaderService {
        "ariaCurrentLink": string;
        "hrefLink": string;
        "textLink": string;
        "titleLink": string;
    }
    interface FrHeaderTools {
    }
    interface FrHeaderToolsLink {
        "hrefLink": string;
        "iconLink": string;
        "targetLink": string;
        "textLink": string;
        "titleLink": string;
    }
    interface FrNavigation {
        "addElement": (element: any) => Promise<void>;
    }
    interface FrSelect {
    }
}
declare global {
    interface HTMLFrAccordionElement extends Components.FrAccordion, HTMLStencilElement {
    }
    var HTMLFrAccordionElement: {
        prototype: HTMLFrAccordionElement;
        new (): HTMLFrAccordionElement;
    };
    interface HTMLFrFooterElement extends Components.FrFooter, HTMLStencilElement {
    }
    var HTMLFrFooterElement: {
        prototype: HTMLFrFooterElement;
        new (): HTMLFrFooterElement;
    };
    interface HTMLFrHeaderElement extends Components.FrHeader, HTMLStencilElement {
    }
    var HTMLFrHeaderElement: {
        prototype: HTMLFrHeaderElement;
        new (): HTMLFrHeaderElement;
    };
    interface HTMLFrHeaderMenuLinksElement extends Components.FrHeaderMenuLinks, HTMLStencilElement {
    }
    var HTMLFrHeaderMenuLinksElement: {
        prototype: HTMLFrHeaderMenuLinksElement;
        new (): HTMLFrHeaderMenuLinksElement;
    };
    interface HTMLFrHeaderServiceElement extends Components.FrHeaderService, HTMLStencilElement {
    }
    var HTMLFrHeaderServiceElement: {
        prototype: HTMLFrHeaderServiceElement;
        new (): HTMLFrHeaderServiceElement;
    };
    interface HTMLFrHeaderToolsElement extends Components.FrHeaderTools, HTMLStencilElement {
    }
    var HTMLFrHeaderToolsElement: {
        prototype: HTMLFrHeaderToolsElement;
        new (): HTMLFrHeaderToolsElement;
    };
    interface HTMLFrHeaderToolsLinkElement extends Components.FrHeaderToolsLink, HTMLStencilElement {
    }
    var HTMLFrHeaderToolsLinkElement: {
        prototype: HTMLFrHeaderToolsLinkElement;
        new (): HTMLFrHeaderToolsLinkElement;
    };
    interface HTMLFrNavigationElement extends Components.FrNavigation, HTMLStencilElement {
    }
    var HTMLFrNavigationElement: {
        prototype: HTMLFrNavigationElement;
        new (): HTMLFrNavigationElement;
    };
    interface HTMLFrSelectElement extends Components.FrSelect, HTMLStencilElement {
    }
    var HTMLFrSelectElement: {
        prototype: HTMLFrSelectElement;
        new (): HTMLFrSelectElement;
    };
    interface HTMLElementTagNameMap {
        "fr-accordion": HTMLFrAccordionElement;
        "fr-footer": HTMLFrFooterElement;
        "fr-header": HTMLFrHeaderElement;
        "fr-header-menu-links": HTMLFrHeaderMenuLinksElement;
        "fr-header-service": HTMLFrHeaderServiceElement;
        "fr-header-tools": HTMLFrHeaderToolsElement;
        "fr-header-tools-link": HTMLFrHeaderToolsLinkElement;
        "fr-navigation": HTMLFrNavigationElement;
        "fr-select": HTMLFrSelectElement;
    }
}
declare namespace LocalJSX {
    interface FrAccordion {
        "toto"?: string;
    }
    interface FrFooter {
    }
    interface FrHeader {
    }
    interface FrHeaderMenuLinks {
        "ariaCurrentLink"?: string;
        "hrefLink"?: string;
        "textLink"?: string;
        "titleLink"?: string;
    }
    interface FrHeaderService {
        "ariaCurrentLink"?: string;
        "hrefLink"?: string;
        "textLink"?: string;
        "titleLink"?: string;
    }
    interface FrHeaderTools {
    }
    interface FrHeaderToolsLink {
        "hrefLink"?: string;
        "iconLink"?: string;
        "targetLink"?: string;
        "textLink"?: string;
        "titleLink"?: string;
    }
    interface FrNavigation {
    }
    interface FrSelect {
    }
    interface IntrinsicElements {
        "fr-accordion": FrAccordion;
        "fr-footer": FrFooter;
        "fr-header": FrHeader;
        "fr-header-menu-links": FrHeaderMenuLinks;
        "fr-header-service": FrHeaderService;
        "fr-header-tools": FrHeaderTools;
        "fr-header-tools-link": FrHeaderToolsLink;
        "fr-navigation": FrNavigation;
        "fr-select": FrSelect;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fr-accordion": LocalJSX.FrAccordion & JSXBase.HTMLAttributes<HTMLFrAccordionElement>;
            "fr-footer": LocalJSX.FrFooter & JSXBase.HTMLAttributes<HTMLFrFooterElement>;
            "fr-header": LocalJSX.FrHeader & JSXBase.HTMLAttributes<HTMLFrHeaderElement>;
            "fr-header-menu-links": LocalJSX.FrHeaderMenuLinks & JSXBase.HTMLAttributes<HTMLFrHeaderMenuLinksElement>;
            "fr-header-service": LocalJSX.FrHeaderService & JSXBase.HTMLAttributes<HTMLFrHeaderServiceElement>;
            "fr-header-tools": LocalJSX.FrHeaderTools & JSXBase.HTMLAttributes<HTMLFrHeaderToolsElement>;
            "fr-header-tools-link": LocalJSX.FrHeaderToolsLink & JSXBase.HTMLAttributes<HTMLFrHeaderToolsLinkElement>;
            "fr-navigation": LocalJSX.FrNavigation & JSXBase.HTMLAttributes<HTMLFrNavigationElement>;
            "fr-select": LocalJSX.FrSelect & JSXBase.HTMLAttributes<HTMLFrSelectElement>;
        }
    }
}
