/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FrAccordion {
    }
    interface FrHeader {
    }
}
declare global {
    interface HTMLFrAccordionElement extends Components.FrAccordion, HTMLStencilElement {
    }
    var HTMLFrAccordionElement: {
        prototype: HTMLFrAccordionElement;
        new (): HTMLFrAccordionElement;
    };
    interface HTMLFrHeaderElement extends Components.FrHeader, HTMLStencilElement {
    }
    var HTMLFrHeaderElement: {
        prototype: HTMLFrHeaderElement;
        new (): HTMLFrHeaderElement;
    };
    interface HTMLElementTagNameMap {
        "fr-accordion": HTMLFrAccordionElement;
        "fr-header": HTMLFrHeaderElement;
    }
}
declare namespace LocalJSX {
    interface FrAccordion {
    }
    interface FrHeader {
    }
    interface IntrinsicElements {
        "fr-accordion": FrAccordion;
        "fr-header": FrHeader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fr-accordion": LocalJSX.FrAccordion & JSXBase.HTMLAttributes<HTMLFrAccordionElement>;
            "fr-header": LocalJSX.FrHeader & JSXBase.HTMLAttributes<HTMLFrHeaderElement>;
        }
    }
}
